version: '3.9'

services:
  inga-api:
    container_name: inga-api
    build:
      context: .
      dockerfile: Api-IngaTasks/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      sql-server:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - ingaTasks



  sql-server:
    container_name: sql-server-ingaTasks
    hostname: sql-server-ingaTasks
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: maringaBRAZIL12
    ports:
      - 1435:1433
    volumes:
      - type: bind
        source: C:/ESTUDO/CSharp/task-time-api/IngaTasks/Api-IngaTasks/Data/mssql/backup
        target: /var/opt/mssql/backups
      - type: bind
        source: C:/ESTUDO/CSharp/task-time-api/IngaTasks/Api-IngaTasks/Data/mssql/data
        target: /var/opt/mssql/data
      - type: bind
        source: C:/ESTUDO/CSharp/task-time-api/IngaTasks/Api-IngaTasks/Data/mssql/log
        target: /var/opt/mssql/log
    networks:
      - ingaTasks

  rabbitmq:
    container_name: rabbitmq-ingaTasks
    hostname: rabbitmq-ingaTasks
    image: rabbitmq:3.13.1-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: maringaBRAZIL12
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - type: bind
        source: C:/ESTUDO/CSharp/task-time-api/IngaTasks/Api-IngaTasks/Data/rabbitmq/data
        target: /var/lib/rabbitmq
      - type: bind
        source: C:/ESTUDO/CSharp/task-time-api/IngaTasks/Api-IngaTasks/Data/rabbitmq/log
        target: /var/log/rabbitmq  
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ingaTasks

  redis:
    container_name: redis-ingaTasks
    hostname: redis-ingaTasks
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command: redis-server --requirepass maringaBRAZIL12 --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - type: bind
        source: C:/ESTUDO/CSharp/task-time-api/IngaTasks/Api-IngaTasks/Data/redis/data
        target: /data
    networks:
      - ingaTasks

networks:
  ingaTasks:
